### ISSUE TITLE
Malformed multipart requests cause an unhandled error

### ISSUE THREAD

**Issue by sgoumaz** [pryv/service-core#415]
How a customer managed to do it:
![bad-multipart](https://user-images.githubusercontent.com/1866533/157703572-f5b1d973-6d10-4795-a5ff-915260ac6000.png)

The error logged by core:
```
2022-03-10 14:16:05 [error]: [api-server-62:Application:error-middleware]: Unhandled API error (Error): Multipart: Boundary not found
Error: Multipart: Boundary not found
    at new Multipart (/app/bin/dist/node_modules/busboy/lib/types/multipart.js:58:11)
    at Multipart (/app/bin/dist/node_modules/busboy/lib/types/multipart.js:26:12)
    at Busboy.parseHeaders (/app/bin/dist/node_modules/busboy/lib/main.js:71:22)
    at new Busboy (/app/bin/dist/node_modules/busboy/lib/main.js:22:10)
    at multerMiddleware (/app/bin/dist/node_modules/multer/lib/make-middleware.js:33:16)
    at hasFileUpload (/app/bin/dist/components/api-server/src/middleware/uploads.js:42:3)
    at Layer.handle [as handle_request] (/app/bin/dist/node_modules/express/lib/router/layer.js:95:5)
    at next (/app/bin/dist/node_modules/express/lib/router/route.js:137:13)
    at /app/bin/dist/components/middleware/src/loadAccess.js:17:7 { context: { location: '/osi182/events', method: 'POST', data: {} } }
```

**Comment by perki** [comment]
service-core has been archived and merged into open-pryv.io (Pryv.io v2). Closing as part of issue-tracker consolidation — this issue stays readable for reference, and anything still relevant to v2 is tracked in https://github.com/pryv/open-pryv.io.
