### ISSUE TITLE
Possible bug in usage of $inc while updating access stats 

### ISSUE THREAD

**Issue by perki** [pryv/service-core#439]
(after upgrade to 1.7.4) Magnes have noticed that when logging in (authenticating) the auth pages show an error very briefly but the authentication process proceeds to be accepted. Checking the logs of the docker instance (pryvio_core) shows:

```
2022-07-21 06:52:51 [error]: [api-server-82:methods:trackingFunctions]: unexpected-error error (500): Unexpected error: '$inc' is empty. You must specify a field like so: {$inc: {<field>: ...}} {
  context: { location: 'p-vescmj8z', method: 'updateAccessLastUsed', data: [] },
  innerError: "MongoError: '$inc' is empty. You must specify a field like so: {$inc: {<field>: ...}}\n" +
    '    at MessageStream.messageHandler (/app/bin/dist/node_modules/mongodb/lib/cmap/connection.js:272:20)\n' +
    '    at MessageStream.emit (node:events:394:28)\n' +
    '    at processIncomingData (/app/bin/dist/node_modules/mongodb/lib/cmap/message_stream.js:144:12)\n' +
    '    at MessageStream._write (/app/bin/dist/node_modules/mongodb/lib/cmap/message_stream.js:42:5)\n' +
    '    at writeOrBuffer (node:internal/streams/writable:389:12)\n' +
    '    at _write (node:internal/streams/writable:330:10)\n' +
    '    at MessageStream.Writable.write (node:internal/streams/writable:334:10)\n' +
    '    at Socket.ondata (node:internal/streams/readable:747:22)\n' +
    '    at Socket.emit (node:events:394:28)\n' +
    '    at addChunk (node:internal/streams/readable:312:12)\n' +
    '    at readableAddChunk (node:internal/streams/readable:287:9)\n' +
    '    at Socket.Readable.push (node:internal/streams/readable:226:10)\n' +
    '    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)'
}
2022-07-21 06:52:51 [error]: [api-server-82:methods:trackingFunctions]: unexpected-error error (500): Unexpected error: '$inc' is empty. You must specify a field like so: {$inc: {<field>: ...}} {
  context: { location: 'p-vescmj8z', method: 'updateAccessLastUsed', data: [] },
  innerError: "MongoError: '$inc' is empty. You must specify a field like so: {$inc: {<field>: ...}}\n" +
    '    at MessageStream.messageHandler (/app/bin/dist/node_modules/mongodb/lib/cmap/connection.js:272:20)\n' +
    '    at MessageStream.emit (node:events:394:28)\n' +
    '    at processIncomingData (/app/bin/dist/node_modules/mongodb/lib/cmap/message_stream.js:144:12)\n' +
    '    at MessageStream._write (/app/bin/dist/node_modules/mongodb/lib/cmap/message_stream.js:42:5)\n' +
    '    at writeOrBuffer (node:internal/streams/writable:389:12)\n' +
    '    at _write (node:internal/streams/writable:330:10)\n' +
    '    at MessageStream.Writable.write (node:internal/streams/writable:334:10)\n' +
    '    at Socket.ondata (node:internal/streams/readable:747:22)\n' +
    '    at Socket.emit (node:events:394:28)\n' +
    '    at addChunk (node:internal/streams/readable:312:12)\n' +
    '    at readableAddChunk (node:internal/streams/readable:287:9)\n' +
    '    at Socket.Readable.push (node:internal/streams/readable:226:10)\n' +
    '    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)'
}
```

**Comment by perki** [comment]
service-core has been archived and merged into open-pryv.io (Pryv.io v2). Closing as part of issue-tracker consolidation — this issue stays readable for reference, and anything still relevant to v2 is tracked in https://github.com/pryv/open-pryv.io.
