### ISSUE TITLE
Pryv.me some events have inconsistent duration values

### ISSUE THREAD

**Issue by perki** [pryv/service-core#448]
When opening pryv.me with user "perki" 

```
What !!  Error: Duration issue.. This should not thappen
    at endTimeFromStoreToDuration (/app/bin/dist/components/mall/src/helpers/eventsUtils.js:55:31)
    at convertEventFromStore (/app/bin/dist/components/mall/src/helpers/eventsUtils.js:186:3)
    at ConvertEventFromStoreStream._transform (/app/bin/dist/components/mall/src/helpers/eventsUtils.js:203:17)
    at ConvertEventFromStoreStream.Transform._write (node:internal/streams/transform:184:23)
    at doWrite (node:internal/streams/writable:408:12)
    at clearBuffer (node:internal/streams/writable:569:7)
    at onwrite (node:internal/streams/writable:461:7)
    at ConvertEventFromStoreStream.Transform._read (node:internal/streams/transform:245:5)
    at ConvertEventFromStoreStream.Readable.read (node:internal/streams/readable:487:10)
    at flow (node:internal/streams/readable:1011:34)
    at emitReadable_ (node:internal/streams/readable:592:3)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
```

**Comment by perki** [comment]
service-core has been archived and merged into open-pryv.io (Pryv.io v2). Closing as part of issue-tracker consolidation — this issue stays readable for reference, and anything still relevant to v2 is tracked in https://github.com/pryv/open-pryv.io.
