### ISSUE TITLE
1.8 Bug when requesting access to ":audit:" stream

### ISSUE THREAD

**Issue by perki** [pryv/service-core#455]
When requesting authorization:

```
[
  {
    "streamId": "*",
    "level": "read"
  },
{
    "streamId": ":audit:",
   "defaultName": "Audit",
    "level": "read"
  }
]
```

We receive the error 

```
{
    "error": {
        "id": "unexpected-error",
        "message": "Unexpected error: Cannot read properties of undefined (reading 'hasFeatureGetParamsExcludedIds')"
    },
    "meta": {
        "apiVersion": "1.8.0-rc6",
        "serverTime": 1665668545.61,
        "serial": "2019061301"
    }
}
```

In the log, the following can be found:

```
2022-10-13 13:42:25 [error]: [api-server-74:Application:error-middleware]: unexpected-error error (500): Unexpected error: Cannot read properties of undefined (reading 'hasFeatureGetParamsExcludedIds') {
  context: {
    location: '/mariana2/accesses/check-app',
    method: 'POST',
    data: {
      requestingAppId: 'app-last-item',
      requestedPermissions: [
        { streamId: '*', level: 'read' },
        { streamId: ':audit:', defaultName: 'Audit', level: 'read' }
      ],
      clientData: {
        'app-web-auth:description': { type: 'note/txt', content: 'This is a consent message.' }
      }
    }
  },
  innerError: "TypeError: Cannot read properties of undefined (reading 'hasFeatureGetParamsExcludedIds')\n" +
    '    at MallUserStreams.get (/app/bin/dist/components/mall/src/MallUserStreams.js:126:33)\n' +
    '    at checkId (/app/bin/dist/components/api-server/src/methods/accesses.js:584:56)\n' +
    '    at checkPermission (/app/bin/dist/components/api-server/src/methods/accesses.js:582:13)\n' +
}
```

**Comment by perki** [comment]
service-core has been archived and merged into open-pryv.io (Pryv.io v2). Closing as part of issue-tracker consolidation — this issue stays readable for reference, and anything still relevant to v2 is tracked in https://github.com/pryv/open-pryv.io.
